In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/student_data.csv")

print(data.head())

   Hours_Studied  Hours_Slept  Pass
0              1            4     0
1              2            5     0
2              2            6     0
3              3            5     0
4              3            6     0


In [3]:
X = data[['Hours_Studied','Hours_Slept']].values

In [4]:
y = data[['Pass']].values

In [5]:
print(X.shape)
print(y.shape)

(20, 2)
(20, 1)


In [6]:
X = X/10

print(X)

[[0.1 0.4]
 [0.2 0.5]
 [0.2 0.6]
 [0.3 0.5]
 [0.3 0.6]
 [0.4 0.6]
 [0.4 0.7]
 [0.5 0.6]
 [0.5 0.7]
 [0.6 0.7]
 [0.6 0.8]
 [0.7 0.8]
 [0.7 0.7]
 [0.8 0.8]
 [0.8 0.9]
 [0.2 0.4]
 [0.3 0.4]
 [0.5 0.8]
 [0.6 0.6]
 [0.1 0.5]]


3-layer neural network.

Input Layer

2 neurons

↓

Hidden Layer 1

5 neurons

↓

Hidden Layer 2

4 neurons

↓

Output Layer

1 neuron

Initialize Weights


In [7]:
np.random.seed(42)

W1 = np.random.randn(2,5)
b1 = np.zeros((1,5))

W2 = np.random.randn(5,4)
b2 = np.zeros((1,4))

W3 = np.random.randn(4,1)
b3 = np.zeros((1,1))

W1: Input → Hidden Layer 1
W2: Hidden Layer 1 → Hidden Layer 2
W3: Hidden Layer 2 → Output

Activation Function

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

Forward Propagation

In [9]:
hidden1 = sigmoid(np.dot(X,W1)+b1)

hidden2 = sigmoid(np.dot(hidden1,W2)+b2)

output = sigmoid(np.dot(hidden2,W3)+b3)

print(output)

[[0.47337562]
 [0.46974553]
 [0.46901281]
 [0.46719325]
 [0.46652362]
 [0.46429549]
 [0.46369708]
 [0.46233358]
 [0.46177522]
 [0.46010931]
 [0.45960799]
 [0.45821354]
 [0.45869242]
 [0.45705115]
 [0.45661727]
 [0.47048668]
 [0.46786968]
 [0.46124497]
 [0.46063564]
 [0.47255783]]


Loss Function

In [10]:
loss = np.mean((y-output)**2)

print("Loss =",loss)

Loss = 0.26294275681543805


Derivative Function

In [11]:
def derivative(x):
    return x*(1-x)

Learning Rate


In [12]:
lr = 0.1

Train the Network

In [13]:
epochs = 5000

for i in range(epochs):

    # Forward
    hidden1 = sigmoid(np.dot(X,W1)+b1)

    hidden2 = sigmoid(np.dot(hidden1,W2)+b2)

    output = sigmoid(np.dot(hidden2,W3)+b3)

    # Loss
    loss = np.mean((y-output)**2)

    # Error
    error = y-output

    d_output = error*derivative(output)

    error2 = d_output.dot(W3.T)

    d_hidden2 = error2*derivative(hidden2)

    error1 = d_hidden2.dot(W2.T)

    d_hidden1 = error1*derivative(hidden1)

    # Update
    W3 += hidden2.T.dot(d_output)*lr

    W2 += hidden1.T.dot(d_hidden2)*lr

    W1 += X.T.dot(d_hidden1)*lr

    if i%500==0:
        print("Epoch:",i," Loss:",loss)

Epoch: 0  Loss: 0.26294275681543805
Epoch: 500  Loss: 0.09424022554997444
Epoch: 1000  Loss: 0.01733051494288388
Epoch: 1500  Loss: 0.008595453981234817
Epoch: 2000  Loss: 0.0052165349239004745
Epoch: 2500  Loss: 0.0035362634068810115
Epoch: 3000  Loss: 0.0025834339415186187
Epoch: 3500  Loss: 0.0019910195478640633
Epoch: 4000  Loss: 0.0015962618453418335
Epoch: 4500  Loss: 0.0013187412928060034


Check Accuracy

In [14]:
prediction = (output>0.5).astype(int)

print(prediction)

[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [15]:
accuracy = np.mean(prediction==y)

print("Accuracy =",accuracy*100,"%")

Accuracy = 100.0 %


Predict New Student

In [16]:
new = np.array([[6,8]])

new = new/10

In [17]:
h1 = sigmoid(np.dot(new,W1)+b1)

h2 = sigmoid(np.dot(h1,W2)+b2)

result = sigmoid(np.dot(h2,W3)+b3)

print(result)

[[0.99925036]]


In [18]:
if result>0.5:
    print("Student Will Pass")
else:
    print("Student Will Fail")

Student Will Pass


In [19]:
new = np.array([[7,4]])

new = new/10

In [20]:
h1 = sigmoid(np.dot(new,W1)+b1)

h2 = sigmoid(np.dot(h1,W2)+b2)

result = sigmoid(np.dot(h2,W3)+b3)

print(result)

[[0.99950516]]


In [21]:
if result<0.5:
    print("Student Will Pass")
else:
    print("Student Will Fail")

Student Will Fail
